/**
 * This file was generated by EverDev.
 * EverDev is a part of EVER OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract TimestampStorage {
    // Contract can have an instance variables.
    // In this example instance variable `timestamp` is used to store the time of `constructor` or `touch`
    // function call
    uint32 public static timestamp;

    // Updates variable `timestamp` with current blockchain time.
    function touch() external {
        // Tells to the TVM that we accept this message.
        tvm.accept();
        // Update timestamp
        timestamp = now;
    }

    // Function returns value of state variable `timestamp`
    function getTimestamp() public view returns (uint32) {
        return timestamp;
    }
}
